package com.agrodrip.utils

object Constants {

    const val SERVER_URL = "https://admin.agrodrip.in/api/"
    const val WEATHER_SERVER_URL = "http://dataservice.accuweather.com/"
    const val MyPREFERENCES = "AgroDrip"

    const val WEATHER_API_KEY = "uzsX5sSRFDBymCASfpTMai2Z6AwTuEO6"
//    const val WEATHER_API_KEY = "mESORcQhxZ6kt0DhtM0Vs1mWXGeSEVCm"
    const val GOOGLE_PLACES_API = "AIzaSyBy1s5mvvrI_jDYu9J9-TlQnhYxVV49i_M"
    const val GOOGLE_DIRECTION_API = "https://maps.googleapis.com/maps/api/"


    var PREF_LANGUAGE_TYPE = "language_type"
    var PREF_LATLONG = "latlong"
    var PREF_UPDATED_LATLONG = "updated_latlong"
    var PREF_PHONE = "mobile"
    var PREF_PROFILE_PIC = "profile_pic"
    var PREF_ROLE_ID = "role_id"
    var PREF_TOKEN = "token"
    var PREF_FIREBASE_TOKEN = "firebase"
    var PREF_ADDRESS = "address"
    var PREF_ADDRESS_ID = "addresid"
    const val PREF_SELECTED_LANGUAGE = "language"
    var PREF_USER_DATA = "user_data"
    var PREF_BADGE = "badge"


    /*api endpoint*/
    const val  SEND_OTP ="sendOtp"
    const val VERIFY_SIGNUP ="otpVerify"
    const val GET_USER ="getUser"
    const val UPDATE_PROFILE ="profileUpdate"
    const val VIDEO_LIST ="videoList"
    const val BANNER_LIST ="banner"
    const val NEWS_LIST ="news"
    const val ISSUE_DRIP ="issueDrip"
    const val GOV_SCHEME ="government"
    const val FERTILIZER_LIST ="fertiliserList"
    const val CROPS_CATEGORY ="cropsCategory"
    const val CROPS_TYPE_LIST ="cropsTypeList"
    const val CROPS_SUB_TYPE_LIST ="cropsTypeSubList"
    const val CROPS_SUB_CATEGORY ="cropsSubCategory"
    const val FEEDBACK ="feedback"
    const val ADD_FARM ="addFarm"
    const val EDIT_FARM ="editFarm"
    const val GET_FARM ="listFarm"
    const val CROP_PROBLEM ="cropsProblem"
    const val CROP_SOLUTION ="solution"
    const val ADD_PRODUCT ="addProduct"
    const val DELETE_PRODUCT ="deleteProduct"
    const val REMOVE_PRODUCT ="removeProduct"
    const val CART_LIST="cartList"
    const val ADD_ADDRESS_LIST="addUserAddress"
    const val EDIT_ADDRESS_LIST="editUserAddress"
    const val ADDRESS_LIST="listUserAddress"
    const val TIPS_LIST="tips"
    const val TOP_PRODUCT_LIST="topProduct"
    const val SUB_PRODUCT_LIST="cropsProduct"
    const val DELETE_FARM_LIST = "deleteFarm"
    const val DELETE_ADDRESS_LIST = "deleteAddress"
    const val ALL_PRODUCT_LIST = "allProduct"
    const val PLACE_ORDER = "addOrder"
    const val ORDER_LIST = "orderList"
    const val ASK_EXPERT = "askExpert"
    const val TALUKA_LIST = "talukaList"
    const val ADD_DRIP_SECTION = "addDrip"
    const val CHANGE_MOBILE = "changeMobile"
    const val UPDATE_MOBILE = "updateMobile"
    const val ADD_PROBLEM = "addCustProblem"

    const val WEATHER_CITY_SEARCH = "locations/v1/cities/geoposition/search"
    const val WEATHER_5_DAYS = "forecasts/v1/daily/5day/"
    const val WEATHER_HOURLY = "forecasts/v1/hourly/1hour/"
}